version: '3.1'

services:

  mongo:
    image: mongo
    container_name: NPC_Database
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: npc_root
      MONGO_INITDB_ROOT_PASSWORD: ImASillyPassword!
      MONGO_INITDB_DATABASE: NPC_Database
